nations: dict[str, str] = {
    'usa': 'USA',
    'usn': 'USA',
    'us': 'USA',
    'united states': 'USA',
    'jp': 'Japan',
    'japan': 'Japan',
    'jpn': 'Japan',
    'ijn': 'Japan',
    'japanese': 'Japan',
    'ger': 'Germany',
    'german': 'Germany',
    'germany': 'Germany',
    'de': 'Germany',
    'deutschland': 'Germany',
    'kms': 'Germany',
    'united kingdom': 'UK',
    'uk': 'UK',
    'british': 'UK',
    'ussr': 'USSR',
    'russia': 'USSR',
    'russian': 'USSR',
    'soviet union': 'USSR',
    'soviet': 'USSR',
    'france': 'France',
    'fr': 'France',
    'french': 'France',
    'mn': 'France',
    'italy': 'Italy',
    'it': 'Italy',
    'rm': 'Italy',
    'italian': 'Italy',
    'pan-asia': 'Pan-Asia',
    'pan-asian': 'Pan-Asia',
    'asian': 'Pan-Asia',
    'pa': 'Pan-Asia',
    'asia': 'Pan-Asia',
    'europe': 'Europe',
    'pan-europe': 'Europe',
    'european': 'Europe',
    'pan-european': 'Europe',
    'eu': 'Europe',
    'pan-america': 'Pan-America',
    'pan-am': 'Pan-America',
    'panam': 'Pan-America',
    'south america': 'Pan-America',
    'sa': 'Pan-America',
    'pan-american': 'Pan-America',
    'cw': 'Commonwealth',
    'commonwealth': 'Commonwealth',
    'anz': 'Commonwealth',
    'aus': 'Commonwealth',
    'australia': 'Commonwealth',
    'australian': 'Commonwealth',
    'nz': 'Commonwealth',
    'new zealand': 'Commonwealth',
    'netherlands': 'Netherlands',
    'nl': 'Netherlands',
    'dutch': 'Netherlands',
    'spain': 'Spain',
    'spanish': 'Spain',
}