class canonicalize:
    Alternates = {
        "G. Kürfurst": "Grosser Kürfurst",
        "G. Kurfurst": "Grosser Kürfurst",
        "GK": "Grosser Kürfurst",
        "Grosser Kurfurst": "Grosser Kürfurst",
        "Großer Kürfurst": "Grosser Kürfurst",
        "Großer Kurfurst": "Grosser Kürfurst",
        "Maaß": "Leberecht Maass",
        "Maass": "Leberecht Maass",
        "Gaede": "Ernst Gaede",
        "FDR": "Franklin D. Roosevelt",
        "F. D. Roosevelt": "Franklin D. Roosevelt",
        "Franklin Delano Roosevelt": "Franklin D. Roosevelt",
        "Roosevelt": "Franklin D. Roosevelt",
        "S. Carolina": "South Carolina",
        "SC": "South Carolina",
        "N. Carolina": "North Carolina",
        "NC": "North Carolina",
        "W. Virginia '41": "West Virginia '41",
        "WV '41": "West Virginia '41",
        "W. Virginia '44": "West Virginia '44",
        "WV '44": "West Virginia '44",
        "Ft. Worth": "Fort WortH",
        "Ft. Worth G": "Fort Worth G",
        "San Martin": "San Martín",
        "Pinatapolis": "Piñatapolis",
        "Yavuz": "Yavuz Sultan Selim",
        "Vasteras": "Västerås",
        "Västeras": "Västerås",
        "Vasterås": "Västerås",
        "Skane": "Skåne",
        "Blyskawica": "Błyskawica",
        "Blyskawica '44": "Błyskawica '44",
        "Blyskawica '52": "Błyskawica '52",
        "Oland": "Öland",
        "Ostergotland": "Östergötland",
        "Östergotland": "Östergötland",
        "Ostergötland": "Östergötland",
        "L. Katsonis": "Lambros Katsonis",
        "Katsonis": "Lambros Katsonis",
        "Jager": "Jäger",
        "Gdansk": "Gdańsk",
        "Ovasen": "Oväsen",
        "Smaland": "Småland",
        "Emile Bertin": "Émile Bertin",
        "Bearn": "Béarn",
        "La Galissoniere": "La Galissonière",
        "La Gal": "La Galissonière",
        "Guepard": "Guépard",
        "Algerie": "Algérie",
        "Republique": "République",
        "Kleber": "Kléber",
        "Konig Albert": "König Albert",
        "Konig": "König",
        "Konigsberg": "Königsberg",
        "Nurnberg": "Nürnberg",
        "Nurnberg '44": "Nürnberg '44",
        "Karl von Schonberg": "Karl von Schönberg",
        "K. Schönberg": "Karl von Schönberg",
        "K. Schonberg": "Karl von Schönberg",
        "Schönberg": "Karl von Schönberg",
        "Schonberg": "Karl von Schönberg",
        "Munchen": "München",
        "Munchen B": "München B",
        "Hipper": "Admiral Hipper",
        "P. Heinrich": "Prinz Heinrich",
        "Heinrich": "Prinz Heinrich",
        "AL P. Heinrich": "AL Prinz Heinrich",
        "AL Heinrich": "AL Prinz Heinrich",
        "P. E. Friedrich": "Prinz Eitel Friedrich",
        "P. Rupprecht": "Prinz Rupprecht",
        "Rupprecht": "Prinz Rupprecht",
        "F. Schultz": "Felix Schultz",
        "Schultz": "Felix Schultz",
        "AL Agir": "AL Ägir",
        "Agir": "Ägir",
        "Blucher": "Blücher",
        "Schroder": "Schröder",
        "Conde": "Condé",
        "G. Hoffman": "Georg Hoffman",
        "Hoffman": "Georg Hoffman",
        "G. Hoffman G": "Georg Hoffman G",
        "Hoffman G": "Georg Hoffman G",
        "M. Immelmann": "Max Immelmann",
        "Susshofen": "Süsshofen",
        "Sußhofen": "Süsshofen",
        "Süßhofen": "Süsshofen",
        "N. Sauro": "Nazario Sauro",
        "Sauro": "Nazario Sauro",
        "D. Alighieri": "Dante Alighieri",
        "Alighieri": "Dante Alighieri",
        "Cavour": "Conte di Cavour",
        "Montecuccoli": "Raimondo Montecuccoli",
        "F. Caracciolo": "Francesco Caracciolo",
        "Caracciolo": "Francesco Caracciolo",
        "F. Ferruccio": "Francesco Ferruccio",
        "Ferruccio": "Francesco Ferruccio",
        "L. Tarigo": "Luca Tarigo",
        "Tarigo": "Luca Tarigo",
        "V. Cuniberti": "Vittorio Cuniberti",
        "Cuniberti": "Vittorio Cuniberti",
        "M. Colonna": "Marcantonio Colonna",
        "Colonna": "Marcantonio Colonna",
        "C. Colombo": "Cristoforo Colombo",
        "Colombo": "Cristoforo Colombo",
        "A. Regolo": "Attilio Regolo",
        "Regolo": "Attilio Regolo",
        "A. da Barbiano": "Alberico da Barbiano",
        "Barbiano": "Alberico da Barbiano",
        "R. Lauria": "Ruggiero di Lauria",
        "Lauria": "Ruggiero di Lauria",
        "F. Gonzaga": "Ferrante Gonzaga",
        "Gonzaga": "Ferrante Gonzaga",
        "Abruzzi": "Duca degli Abruzzi",
        "d'Aosta": "Duca d'Aosta",
        "Aosta": "Duca d'Aosta",
        "Tenryu": "Tenryū",
        "Tenryuu": "Tenryū",
        "Myogi": "Myōgi",
        "Myougi": "Myōgi",
        "Hosho": "Hōshō",
        "Hōsho": "Hōshō",
        "Hoshō": "Hōshō",
        "Houshou": "Hōshō",
        "Hoshou": "Hōshō",
        "Housho": "Hōshō",
        "Yubari": "Yūbari",
        "Yuubari": "Yūbari",
        "Kongo": "Kongō",
        "Kongou": "Kongō",
        "ARP Kongo": "ARP Kongō",
        "ARP Kongou": "ARP Kongō",
        "Fujin": "Fūjin",
        "Fuujin": "Fūjin",
        "Fuso": "Fusō",
        "Fusou": "Fusō",
        "Ryujo": "Ryūjō",
        "Ryūjo": "Ryūjō",
        "Ryujō": "Ryūjō",
        "Ryuujou": "Ryūjō",
        "Ryujou": "Ryūjō",
        "Ryuujo": "Ryūjō",
        "Myoko": "Myōkō",
        "Myōko": "Myōkō",
        "Myokō": "Myōkō",
        "Myoukou": "Myōkō",
        "Myouko": "Myōkō",
        "Myokou": "Myōkō",
        "ARP Myoko": "ARP Myōkō",
        "ARP Myōko": "ARP Myōkō",
        "ARP Myokō": "ARP Myōkō",
        "ARP Myoukou": "ARP Myōkō",
        "ARP Myouko": "ARP Myōkō",
        "ARP Myokou": "ARP Myōkō",
        "Hyuga": "Hyūga",
        "Hyuuga": "Hyūga",
        "Yudachi": "Yūdachi",
        "Yuudachi": "Yūdachi",
        "Kagero": "Kagerō",
        "Kagerou": "Kagerō",
        "Shokaku": "Shōkaku",
        "Shoukaku": "Shōkaku",
        "Yugumo": "Yūgumo",
        "Yuugumo": "Yūgumo",
        "Zao": "Zaō",
        "Zaou": "Zaō",
        "Zao CLR": "Zaō CLR",
        "Zaou CLR": "Zaō CLR",
        "Hakuryu": "Hakuryū",
        "Hakuryuu": "Hakuryū",
        "De 7 Provincien": "De 7 Provinciën",
        "D7P": "De 7 Provinciën",
        "De Zeven Provincien": "De 7 Provinciën",
        "DZP": "De 7 Provinciën",
        "De Zeven Provinciën": "De 7 Provinciën",
        "M. van Coehoorn": "Menno van Coehoorn",
        "Hercules": "Hércules",
        "Alm. Barroso": "Almirante Barroso",
        "Alm. Abreu": "Almirante Abreu",
        "Jurua": "Juruá",
        "Cordoba": "Córdoba",
        "Almte. Cochrane": "Almirante Cochrane",
        "Cnel. Bolognesi": "Coronel Bolognesi",
        "Colonel Bolognesi": "Coronel Bolognesi",
        "I. Allende": "Ignacio Allende",
        "Allende": "Ignacio Allende",
        "Almte. Grau": "Almirante Grau",
        "Atlantico": "Atlântico",
        "C. Aguirre": "Comandante Aguirre",
        "Valparaiso": "Valparaíso",
        "Almte. Villar": "Almirante Villar",
        "Almte. Irízar": "Almirante Irízar",
        "Almirante Irizar": "Almirante Irízar",
        "Almte. Irizar": "Almirante Irízar",
        "Pinatian": "Piñatian",
        "Lushun": "Lüshun",
        "Lushun B": "Lüshun B",
        "Cataluna": "Cataluña",
        "Andalucia": "Andalucía",
        "Almte. Oquendo": "Almirante Oquendo",
        "Alvaro de Bazan": "Álvaro de Bazán",
        "Álvaro de Bazan": "Álvaro de Bazán",
        "Alvaro de Bazán": "Álvaro de Bazán",
        "de Bazán": "Álvaro de Bazán",
        "de Bazan": "Álvaro de Bazán",
        "Bazán": "Álvaro de Bazán",
        "Bazan": "Álvaro de Bazán",
        "Alvaro": "Álvaro de Bazán",
        "Álvaro": "Álvaro de Bazán",
        "Jupiter": "Júpiter",
        "Mendez Nunez": "Méndez Núñez",
        "Méndez Nunez": "Méndez Núñez",
        "Mendez Núnez": "Méndez Núñez",
        "Mendez Nuñez": "Méndez Núñez",
        "Méndez Núnez": "Méndez Núñez",
        "Mendez Núñez": "Méndez Núñez",
        "Méndez Nuñez": "Méndez Núñez",
        "Núñez": "Méndez Núñez",
        "Nunez": "Méndez Núñez",
        "Núnez": "Méndez Núñez",
        "Nuñez": "Méndez Núñez",
        "Almte. Cervera": "Almirante Cervera",
        "Zarya S.": "Zarya Svobody",
        "Dm. Donskoi": "Dmitri Donskoi",
        "Donskoi": "Dmitri Donskoi",
        "A. Nevsky": "Alexander Nevsky",
        "Nevsky": "Alexander Nevsky",
        "Nikolai I": "Imperator Nikolai I",
        "Okt. Revolutsiya": "Oktyabrskaya Revolutsiya",
        "D. Pozharsky": "Dmitri Pozharsky",
        "Dm. Pozharsky": "Dmitri Pozharsky",
        "P. Bagration": "Pyotr Bagration",
        "SYS": "Sun Yat-Sen",
        "Sov. Soyuz": "Sovetsky Soyuz",
        "AL Sov. Rossiya": "AL Sovetskaya Rossiya",
        "Sov. Rossiya": "Sovetskaya Rossiya",
        "V. Guerrero": "Vicente Guerrero",
        "Chateaurenault": "Châteaurenault",
        "N. Carolina CLR": "North Carolina CLR",
        "NC CLR": "North Carolina CLR",
        "E. Loewenhardt": "Erich Loewenhardt",
        "M. Richtofen": "Manfred von Richtofen",
        "MvR": "Manfred von Richtofen",
        "MVR": "Manfred von Richtofen",
        "Cuauhtemoc": "Cuauhtémoc",
        "FdG": "Friedrich der Grosse",
        "FDG": "Friedrich der Grosse",
        "F. Sherman": "Forrest Sherman",
        "Sherman": "Forrest Sherman",
        "G. J. Maerker": "Gustav Julius Maerker",
        "Maerker": "Gustav Julius Maerker",
        "E. Dragon": "Eastern Dragon",
        "S. Dragon": "Southern Dragon",
        "Scheer": "Admiral Scheer",
        "S. Thunder": "Scarlet Thunder",
    }

    def __new__(cls, ship_name: str) -> str:
        return cls.Alternates.get(ship_name, ship_name)